# SPMC-Timeslicing-GPU: a single pod's multiple containers share a GPU via TimeSlicing.

# The pod will be running.
# $ kubectl get pods -n spmc-timeslicing-gpu-test
# NAME      READY   STATUS    RESTARTS   AGE
# gpu-pod   1/1     Running   0          10s
#
# # Run `nvidia-smi` will show something like the following:
# +---------------------------------------------------------------------------------------+
# | Processes:                                                                            |
# |  GPU   GI   CI        PID   Type   Process name                            GPU Memory |
# |        ID   ID                                                             Usage      |
# |=======================================================================================|
# |    0   N/A  N/A   1575573      C   /cuda-samples/sample                        746MiB |
# +---------------------------------------------------------------------------------------+

---
apiVersion: v1
kind: Namespace
metadata:
  name: spmc-timeslicing-gpu-test

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaim
metadata:
  namespace: spmc-timeslicing-gpu-test
  name: gpu-ts-sharing-0
spec:
  resourceClassName: gpu.nvidia.com
  parametersRef:
    apiGroup: gpu.resource.nvidia.com
    kind: GpuClaimParameters
    name: gpu-ts-sharing

---
apiVersion: resource.k8s.io/v1alpha2
kind: ResourceClaim
metadata:
  namespace: spmc-timeslicing-gpu-test
  name: gpu-ts-sharing-1
spec:
  resourceClassName: gpu.nvidia.com
  parametersRef:
    apiGroup: gpu.resource.nvidia.com
    kind: GpuClaimParameters
    name: gpu-ts-sharing

---
apiVersion: gpu.resource.nvidia.com/v1alpha1
kind: GpuClaimParameters
metadata:
  namespace: spmc-timeslicing-gpu-test 
  name: gpu-ts-sharing
spec:
  sharing:
    strategy: TimeSlicing 

---
apiVersion: v1
kind: Pod
metadata:
  namespace: spmc-timeslicing-gpu-test
  name: gpu-pod
  labels:
    app: pod
spec:
  containers:
  - name: ctr0
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    args: ["--benchmark", "--numbodies=2560000"]
    resources:
      claims:
      - name: gpu0
  containers:
  - name: ctr1
    image: nvcr.io/nvidia/k8s/cuda-sample:nbody-cuda11.7.1-ubuntu18.04
    args: ["--benchmark", "--numbodies=2560000"]
    resources:
      claims:
      - name: gpu1
  resourceClaims:
  - name: gpu0
    source:
      resourceClaimName: gpu-ts-sharing-0
  resourceClaims:
  - name: gpu1
    source:
      resourceClaimName: gpu-ts-sharing-1
